apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant4
spec:
  description: 'Tenant 4 Workloads'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Tenant 4 Administrators
      groups:
        - tenant4-admins
      name: tenant4-admin
      policies:
        - 'p, proj:tenant4:tenant4-admin, applications, *, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-admin, applicationsets, *, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-admin, clusters, *, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-admin, repositories, *, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-admin, logs, *, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-admin, exec, *, tenant4/*, allow'
    - description: Tenant 4 Users
      groups:
        - tenant4-users
      name: tenant4-user
      policies:
        - 'p, proj:tenant4:tenant4-user, applications, get, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-user, applications, sync, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-user, repositories, get, tenant4/*, allow'
        - 'p, proj:tenant4:tenant4-user, logs, *, tenant4/*, allow'
  sourceRepos:
    - 'https://github.com/fwalker-redhat/gitops-demo.git'