apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tnsfile-secret
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
  - name: tnsnames
    files:
      - tnsnames.ora
