apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hydrate: normal
    argocd.argoproj.io/sync-wave: "1"
  name: multitenant-gitops
spec:
  destination:
    namespace: multitenant-gitops
    server: 'https://kubernetes.default.svc'
  project: gitops-instances
  source:
    path: argocds/kustomize/overlays/multitenant
    repoURL: 'https://github.com/fwalker-redhat/gitops-demo.git'
    targetRevision: namespaces-dev-only
  syncPolicy:
    syncOptions:
      - Delete=confirm
      - ApplyOutOfSyncOnly=true