apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hydrate: normal
    argocd.argoproj.io/sync-wave: "1"
  name: argo-rollout-manager
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: gitops-instances
  source:
    path: argorollouts/rollout-manager
    repoURL: 'https://github.com/fwalker-redhat/gitops-demo.git'
    targetRevision: rollouts-start
  syncPolicy:
    syncOptions:
      - Delete=confirm
      - ApplyOutOfSyncOnly=true