apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hydrate: normal
  name: team-gitops
spec:
  destination:
    namespace: team-gitops
    server: 'https://kubernetes.default.svc'
  project: gitops-instances
  source:
    kustomize: {}
    path: argocds/kustomize/overlays/singletenant
    repoURL: 'https://github.com/fwalker-redhat/gitops-demo.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Delete=false