apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-gitops
resources:
  - ../../base
  - rolebindings/openshift-gitops-controller-argocds.yaml
  - rolebindings/openshift-gitops-controller-appprojects.yaml
  - projects/tenant4.yaml
patches:
  - path: argocd-applicationset.yaml
    target:
      group: argoproj.io
      version: v1beta1
      kind: ArgoCD
      name: gitops
  - patch: |-
      - op: replace
        path: /metadata/name
        value: team-gitops
    target:
      group: argoproj.io
      version: v1beta1
      kind: ArgoCD
      name: gitops
      