apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multitenant-gitops
resources:
  - ../../base
  - projects/tenant1.yaml
  - projects/tenant2.yaml
  - projects/tenant3.yaml
patches:
  - path: argocd-applicationset.yaml
    target:
      group: argoproj.io
      version: v1beta1
      kind: ArgoCD
      name: gitops
  - patch: |-
      - op: replace
        path: /metadata/name
        value: multitenant-gitops
    target:
      group: argoproj.io
      version: v1beta1
      kind: ArgoCD
      name: gitops
